### ISSUE TITLE
TTN Mapper webhook not working.

### ISSUE THREAD

**Issue by wizzfizz94** [ttnmapper/documentation#1]
My device's payload formater looks like this:

```js
function decodeUplink(input) {
  return {
    data: {
      latitude: -38.12,
      longitude: 151.91,
      altitude: 0,
      sats: 0
    },
    warnings: [],
    errors: []
  };
}
```

I have setup the TTN Mapper webhook as well:
![webhook](https://user-images.githubusercontent.com/13703641/116667570-ed07ca80-a9ce-11eb-8684-762614d18373.png)

I can also confirm i'm receiving up links from the device but when i look at advanced maps for this device or experiment it is empty.

**Comment by jpmeijers** [comment]
Yes you are absolutely right. The URL in the webhook template is wrong. I'm currently busy investigating a workaround to do a redirect from the incorrect to the correct URL as a temporary fix.

A proper fix is to replace the base url:
From `https://ttnmapper.org/integrations/tts/v3` to `https://integrations.ttnmapper.org/tts/v3`

Can you please try this and confirm if it works. I'll continue investigation a workaround, but I will also file a fix for the webhook template later today - but these can take weeks to update.

**Comment by wizzfizz94** [comment]
@jpmeijers thanks for the response.
I tried replacing the url but i'm still not getting any data plotted in the TTN Mapper.
I can also see the Payload JSON in the live data stream so i can confirm the decoding is working.

**Comment by wizzfizz94** [comment]
Ok so i can see a couple of data entries for my device if I get the CSV data for my device from https://ttnmapper.org/advanced-maps/ by specifying the device ID but i can not view the measurements on the map and i can not locate my experiment name in the experiment list or by specifying the experiment ID from advanced maps.

**Comment by jpmeijers** [comment]
Many of these features are not yet implemented. Please keep an eye on https://docs.ttnmapper.org/project_status.html
