### ISSUE TITLE
Advanced Maps Gateway Data not correct

### ISSUE THREAD

**Issue by liflitz** [ttnmapper/documentation#11]
I had a mobile device next to my stationary gateway for a day, then put my device in my car and drove with it 200 km. In Advanced Maps, the Device Data nicely shows me where my device picked up which other gateways on the way. However, the Gateway Data shows all of these measuring points as well claiming that my stationary gateway made all these connections to my mobile device up to 200 km away (and a mountain in between ...). - This was an extreme case, but I have seen similar (in my opinion incorrect) behaviours of the TTN Mapper on other occasions as well.

**Comment by jpmeijers** [comment]
This is likely an issue with the respective gateway, or the way you are mapping. Please email info@ttnmapper.org with more details so we can investigate.

**Comment by liflitz** [comment]
Done – thanks!!!

 

Von: JP Meijers ***@***.***> 
Gesendet: Dienstag, 27. Februar 2024 13:25
An: ttnmapper/documentation ***@***.***>
Cc: liflitz ***@***.***>; Author ***@***.***>
Betreff: Re: [ttnmapper/documentation] Advanced Maps Gateway Data not correct (Issue #11)

 

This is likely an issue with the respective gateway, or the way you are mapping. Please email ***@***.*** ***@***.***>  with more details so we can investigate.
